wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.19.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1753194149
    t:
      1:
      - 1
      - 53
      - 55
      2:
      - 1
      - 53
      - 55
      3:
      - 14
      - 23
      - 37
      - 61
      4: 3.10.12
      5: 0.19.1
      8:
      - 3
      - 8
      13: windows-amd64
clip_param:
  desc: null
  value: 0.06537788711110364
entropy_coef:
  desc: null
  value: 0.09677847848917448
gae_lambda:
  desc: null
  value: 0.9798840242164272
lr:
  desc: null
  value: 0.00012821656313541764
ppo_epoch:
  desc: null
  value: 4
