program: start_hyperparameter_tuning.py
method: bayes
metric:
  name: avg_episode_return
  goal: maximize

parameters:
  lr:
    distribution: uniform
    min: 0.00003
    max: 0.00004

  entropy_coef:
    distribution: uniform
    min: 0.02
    max: 0.04

  ppo_epoch:
    distribution: q_uniform
    min: 3
    max: 4
    q: 1

  gae_lambda:
    distribution: uniform
    min: 0.92
    max: 0.94

  clip_param:
    distribution: uniform
    min: 0.02
    max: 0.04